[package]
name = "cdp-improved"
version = "0.1.0"
edition = "2021"

[dependencies]
chromiumoxide = "0.7.0"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"