[package]
name = "cdp-improved"
version = "0.1.0"
edition = "2021"

[dependencies]
scraper = "0.12"
tokio = { version = "1", features = ["full"] }
chromiumoxide = "0.5"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
futures = "0.3"  # Add this line
dotenv = "0.15.0"
